"""add users table and optional catch.user.id

Revision ID: 00b4e88a8682
Revises: ade2c3647039
Create Date: 2025-12-17 12:27:28.894678

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00b4e88a8682"
down_revision = "ade2c3647039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("catches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_catches_user_id_users", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catches", schema=None) as batch_op:
        batch_op.drop_constraint("fk_catches_user_id_users", type_="foreignkey")
        batch_op.drop_column("user_id")

    op.drop_table("users")
    # ### end Alembic commands ###
